IF
  Detect(Myself)
  Global("bd_no_combat","locals",2)
THEN
  RESPONSE #100
    NoAction()
END

IF
  Global("bd_no_retreat","locals",0)
  Global("bd_retreat","locals",1)
  Global("bd_no_combat","locals",1)
  Global("bd_combat","locals",0)
THEN
  RESPONSE #100
    NoAction()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_ARMOR_OF_FAITH)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_ARMOR_OF_FAITH)
    ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_PROTECT_FROM_EVIL)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_PROTECT_FROM_EVIL)
    ReallyForceSpell(Myself,CLERIC_PROTECT_FROM_EVIL)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_AID)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_AID)
    ReallyForceSpell(Myself,CLERIC_AID)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_SPIRITUAL_HAMMER)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_SPIRITUAL_HAMMER)
    ReallyForceSpell(Myself,CLERIC_SPIRITUAL_HAMMER)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_DEFENSIVE_HARMONY)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_DEFENSIVE_HARMONY)
    ReallyForceSpell(Myself,CLERIC_DEFENSIVE_HARMONY)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)
    ReallyForceSpell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_RIGHTEOUS_MAGIC)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_RIGHTEOUS_MAGIC)
    ReallyForceSpell(Myself,CLERIC_RIGHTEOUS_MAGIC)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(NPC_BLADE_BARRIER)
THEN
  RESPONSE #100
    RemoveSpell(NPC_BLADE_BARRIER)
    ReallyForceSpell(Myself,NPC_BLADE_BARRIER)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_RESIST_FIRE)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_RESIST_FIRE)
    ReallyForceSpell(Myself,CLERIC_RESIST_FIRE)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_PROTECTION_FROM_EVIL)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_EVIL)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_BLUR)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_BLUR)
    ReallyForceSpell(Myself,WIZARD_BLUR)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_FIRE_SHIELD_BLUE)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_FIRE_SHIELD_BLUE)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_FIRE_SHIELD_RED)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_FIRE_SHIELD_RED)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_SPIRIT_ARMOR)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_SPIRIT_ARMOR)
    ReallyForceSpell(Myself,WIZARD_SPIRIT_ARMOR)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_SHIELD)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_SHIELD)
    ReallyForceSpell(Myself,WIZARD_SHIELD)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_PHYSICAL_MIRROR)
  OR(3)
    RandomNum(2,1)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_PHYSICAL_MIRROR)
    ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
  !HaveSpell(CLERIC_PHYSICAL_MIRROR)
  OR(3)
    RandomNum(2,1)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
  !HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
  !HaveSpell(CLERIC_PHYSICAL_MIRROR)
  OR(3)
    RandomNum(2,1)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_STONE_SKIN)
  OR(3)
    RandomNum(2,2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_STONE_SKIN)
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_MIRROR_IMAGE)
  !HaveSpell(WIZARD_STONE_SKIN)
  OR(3)
    RandomNum(2,2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_SHADOW_DOOR)
  !HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
  OR(3)
    RandomNumLT(4,3)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_SHADOW_DOOR)
    ReallyForceSpell(Myself,WIZARD_SHADOW_DOOR)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
  OR(3)
    RandomNumLT(4,3)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_IMPROVED_INVISIBILITY)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
  OR(3)
    RandomNumGT(4,2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
    ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  !HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
  OR(3)
    RandomNumGT(4,2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
    ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_SHIELD_OF_THE_ARCHONS)
  !HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  !HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
  OR(3)
    RandomNumGT(4,2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_SHIELD_OF_THE_ARCHONS)
    ReallyForceSpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_MINOR_SPELL_TURNING)
  !HaveSpell(CLERIC_SHIELD_OF_THE_ARCHONS)
  !HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  !HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
  OR(3)
    RandomNumGT(4,2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_MINOR_SPELL_TURNING)
    ReallyForceSpell(Myself,WIZARD_MINOR_SPELL_TURNING)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
  !HaveSpell(WIZARD_MINOR_SPELL_TURNING)
  !HaveSpell(CLERIC_SHIELD_OF_THE_ARCHONS)
  !HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  !HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
  OR(3)
    RandomNumGT(4,2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
    ReallyForceSpell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_MAGIC_RESISTANCE)
  OR(3)
    RandomNumLT(6,4)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_MAGIC_RESISTANCE)
    ReallyForceSpell(Myself,CLERIC_MAGIC_RESISTANCE)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_FREE_ACTION)
  OR(3)
    RandomNumGT(6,3)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    RemoveSpell(CLERIC_FREE_ACTION)
    ReallyForceSpell(Myself,CLERIC_FREE_ACTION)
    Continue()
END

IF
  Global("bd_prebuff","locals",0)
  Detect(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobal("bd_prebuff","locals",1)
    SetGlobalTimer("bd_defence_timer","locals",4)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,SANCTUARY)
  See(NearestEnemyOf(Myself))
  OR(5)
    HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
    HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
    HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
    HasItem("potn52",Myself)  // ~Potion of Extra Healing~
    HasItem("potn08",Myself)  // ~Potion of Healing~
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_SANCTUARY)
  !StateCheck(Myself,STATE_SILENCED)
  HPPercentLT(Myself,65)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    RemoveSpell(CLERIC_SANCTUARY)
    ForceSpell(Myself,CLERIC_SANCTUARY)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  StateCheck(Myself,STATE_POISONED)
  HaveSpell(CLERIC_NEUTRALIZE_POISON)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    RemoveSpell(CLERIC_NEUTRALIZE_POISON)
    ForceSpell(Myself,CLERIC_NEUTRALIZE_POISON)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  StateCheck(Myself,STATE_POISONED)
  HaveSpell(CLERIC_SLOW_POISON)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    RemoveSpell(CLERIC_SLOW_POISON)
    ForceSpell(Myself,CLERIC_SLOW_POISON)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  StateCheck(Myself,STATE_POISONED)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn17",Myself)  // ~Elixir of Health~
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn17",Myself)  // ~Elixir of Health~
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  StateCheck(Myself,STATE_POISONED)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn20",Myself)  // ~Antidote~
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn20",Myself)  // ~Antidote~
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Range(NearestEnemyOf(Myself),30)
  HaveSpell(CLERIC_MASS_CURE)
  OR(4)
    HPPercentLT(NearestAllyOf(Myself),65)
    HPPercentLT(SecondNearestAllyOf(Myself),65)
    HPPercentLT(ThirdNearestAllyOf(Myself),65)
    HPPercentLT(FourthNearestAllyOf(Myself),65)
  OR(4)
    HPPercentLT(Myself,80)
    Range(EighthNearestAllyOf(Myself),20)
    HPPercentLT(FifthNearestAllyOf(Myself),65)
    HPPercentLT(SixthNearestAllyOf(Myself),65)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_MASS_CURE)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(3)
    !See(NearestEnemyOf(Myself))
    StateCheck(Myself,STATE_NOT_TARGETABLE)
    CheckStat(Myself,1,SANCTUARY)
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  HPPercentLT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(3)
    !See(NearestEnemyOf(Myself))
    StateCheck(Myself,STATE_NOT_TARGETABLE)
    CheckStat(Myself,1,SANCTUARY)
  HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
  HPPercentLT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_CURE_SERIOUS_WOUNDS)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(3)
    !See(NearestEnemyOf(Myself))
    StateCheck(Myself,STATE_NOT_TARGETABLE)
    CheckStat(Myself,1,SANCTUARY)
  HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
  HPPercentLT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_CURE_MEDIUM_WOUNDS)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(3)
    !See(NearestEnemyOf(Myself))
    StateCheck(Myself,STATE_NOT_TARGETABLE)
    CheckStat(Myself,1,SANCTUARY)
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  HPPercentLT(Myself,80)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn52",Myself)  // ~Potion of Extra Healing~
  HPPercentLT(Myself,75)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn52",Myself)  // ~Potion of Extra Healing~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn08",Myself)  // ~Potion of Healing~
  HPPercentLT(Myself,80)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn08",Myself)  // ~Potion of Healing~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_VOCALIZE)
  StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_VOCALIZE)
END

IF
  CheckStat(Myself,1,SANCTUARY)
  HPPercentLT(Myself,80)
  OR(6)
    HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
    HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
    HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
    HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
    HasItem("potn52",Myself)  // ~Potion of Extra Healing~
    HasItem("potn08",Myself)  // ~Potion of Healing~
  See(NearestEnemyOf(Myself))
  DifficultyGT(EASIEST)
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_innates","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  See(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn35",Myself)  // ~Potion of Magic Shielding~
  CheckStatGT(Myself,-5,SAVEVSSPELL)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn35",Myself)  // ~Potion of Magic Shielding~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_innates","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  See(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn34",Myself)  // ~Potion of Magic Protection~
  CheckStatLT(Myself,20,RESISTMAGIC)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn34",Myself)  // ~Potion of Magic Protection~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_innates","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  See(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn21",Myself)  // ~Potion of Clarity~
  CheckStat(Myself,0,CLERIC_CHAOTIC_COMMANDS)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn21",Myself)  // ~Potion of Clarity~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_innates","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  See(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn45",Myself)  // ~Potion of Freedom~
  CheckStat(Myself,0,CLERIC_FREE_ACTION)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn45",Myself)  // ~Potion of Freedom~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_innates","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  See(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn24",Myself)  // ~Potion of Defense~
  CheckStatGT(Myself,0,ARMORCLASS)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn24",Myself)  // ~Potion of Defense~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_innates","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  See(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn19",Myself)  // ~Potion of Agility~
  CheckStatLT(Myself,18,DEX)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn19",Myself)  // ~Potion of Agility~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_innates","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  See(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn37",Myself)  // ~Potion of Mind Focusing~
  CheckStatLT(Myself,19,DEX)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn37",Myself)  // ~Potion of Mind Focusing~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_innates","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  See(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn28",Myself)  // ~Potion of Fortitude~
  CheckStatLT(Myself,18,CON)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn28",Myself)  // ~Potion of Fortitude~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_innates","locals",0)
  See(NearestEnemyOf(Myself))
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HasItem("potn14",Myself)  // ~Oil of Speed~
  !StateCheck(Myself,STATE_HASTED)
  CheckStat(Myself,0,IMPROVEDHASTE)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn14",Myself)  // ~Oil of Speed~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  CheckStat(Myself,0,STONESKINS)
  Detect(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_STONE_SKIN)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_STONE_SKIN)
  RESPONSE #35
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  CheckStat(Myself,0,STONESKINS)
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MIRROR_IMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_MIRROR_IMAGE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !CheckSpellState(Myself,BUFF_PRO_WEAPONS)
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !CheckSpellState(Myself,BUFF_PRO_WEAPONS)
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_PHYSICAL_MIRROR)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_PHYSICAL_MIRROR)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !CheckSpellState(Myself,BUFF_PRO_WEAPONS)
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !CheckSpellState(Myself,BUFF_PRO_SPELLS)
  HaveSpell(CLERIC_SHIELD_OF_THE_ARCHONS)
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !CheckSpellState(Myself,BUFF_PRO_SPELLS)
  HaveSpell(WIZARD_MINOR_SPELL_TURNING)
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_MINOR_SPELL_TURNING)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !CheckSpellState(Myself,BUFF_PRO_SPELLS)
  HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !CheckSpellState(Myself,BUFF_PRO_SPELLS)
  HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !CheckSpellState(Myself,BUFF_PRO_SPELLS)
  HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(Myself,CANNOT_TURN_INVISIBLE)
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MISLEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_MISLEAD)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(Myself,CANNOT_TURN_INVISIBLE)
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SHADOW_DOOR)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_SHADOW_DOOR)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Global("bd_no_defense","locals",0)
  !GlobalTimerNotExpired("bd_defence_timer","locals")
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(Myself,CANNOT_TURN_INVISIBLE)
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_defence_timer","locals",THREE_MINUTES)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    HaveSpell(WIZARD_CHAIN_LIGHTNING)
    HasItem("scrl7s",Myself)  // scrl7s
  OR(2)
    !See(NearestEnemyOf(Myself))
    !TriggerOverride(NearestEnemyOf(Myself),Range(NearestAllyOf(Myself),13))
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !TriggerOverride(SecondNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),13))
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !TriggerOverride(ThirdNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),13))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),13))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_CHAIN_LIGHTNING)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HasItem("scrl7s",Myself)  // scrl7s
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),13))
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("scrl7s",LastSeenBy)  // scrl7s
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  HaveSpell(CLERIC_HOLY_SMITE)
  OR(2)
    !See(NearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]))
    TriggerOverride(NearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),22))
  OR(2)
    !See(SecondNearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),22))
  OR(2)
    !See(ThirdNearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]))
    TriggerOverride(ThirdNearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),22))
  OR(2)
    !See(FourthNearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]))
    TriggerOverride(FourthNearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),22))
  OR(2)
    !See(FifthNearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]))
    TriggerOverride(FifthNearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),22))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_HOLY_SMITE)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !TriggerOverride(LastSeenBy,Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]),22))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_HOLY_SMITE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  HaveSpell(CLERIC_UNHOLY_BLIGHT)
  OR(2)
    !See(NearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]))
    TriggerOverride(NearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),22))
  OR(2)
    !See(SecondNearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),22))
  OR(2)
    !See(ThirdNearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]))
    TriggerOverride(ThirdNearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),22))
  OR(2)
    !See(FourthNearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]))
    TriggerOverride(FourthNearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),22))
  OR(2)
    !See(FifthNearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]))
    TriggerOverride(FifthNearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),22))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_UNHOLY_BLIGHT)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !TriggerOverride(LastSeenBy,Range(NearestEnemyOfType([0.0.0.0.0.0.MASK_GOOD]),22))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_UNHOLY_BLIGHT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  DifficultyGT(EASY)
  OR(5)
    HaveSpell(WIZARD_FIREBALL)
    HaveSpell(WIZARD_SKULL_TRAP)
    HaveSpell(CLERIC_GLYPH_OF_WARDING)
    HasItem("wand05",Myself)  // ~Wand of Fire~
    HasItem("potn26",Myself)  // ~Potion of Explosions~
  OR(3)
    !See(FarthestEnemyOf(Myself))
    !TriggerOverride(FarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(FarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  OR(3)
    !See(SecondFarthestEnemyOf(Myself))
    !TriggerOverride(SecondFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(SecondFarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  OR(3)
    !See(ThirdFarthestEnemyOf(Myself))
    !TriggerOverride(ThirdFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(ThirdFarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  OR(3)
    !See(FourthFarthestEnemyOf(Myself))
    !TriggerOverride(FourthFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(FourthFarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  OR(3)
    !See(FifthFarthestEnemyOf(Myself))
    !TriggerOverride(FifthFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(FifthFarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  OR(3)
    !See(SixthFarthestEnemyOf(Myself))
    !TriggerOverride(SixthFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(SixthFarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  OR(3)
    !See(SeventhFarthestEnemyOf(Myself))
    !TriggerOverride(SeventhFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(SeventhFarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  OR(3)
    !See(EighthFarthestEnemyOf(Myself))
    !TriggerOverride(EighthFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(EighthFarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  OR(3)
    !See(NinthFarthestEnemyOf(Myself))
    !TriggerOverride(NinthFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(NinthFarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  OR(3)
    !See(TenthFarthestEnemyOf(Myself))
    !TriggerOverride(TenthFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    TriggerOverride(TenthFarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  DifficultyGT(EASY)
  HaveSpell(WIZARD_FIREBALL)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),15))
  !TriggerOverride(LastSeenBy,Range(NearestEnemyOf(Myself),22))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_FIREBALL)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  DifficultyGT(EASY)
  HaveSpell(WIZARD_SKULL_TRAP)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),15))
  !TriggerOverride(LastSeenBy,Range(NearestEnemyOf(Myself),22))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_SKULL_TRAP)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  DifficultyGT(EASY)
  HaveSpell(CLERIC_GLYPH_OF_WARDING)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),15))
  !TriggerOverride(LastSeenBy,Range(NearestEnemyOf(Myself),22))
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_GLYPH_OF_WARDING)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  DifficultyGT(EASY)
  HasItem("wand05",Myself)  // ~Wand of Fire~
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),15))
  !TriggerOverride(LastSeenBy,Range(NearestEnemyOf(Myself),22))
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("wand05",LastSeenBy)  // ~Wand of Fire~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  DifficultyGT(EASY)
  HasItem("potn26",Myself)  // ~Potion of Explosions~
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),15))
  !TriggerOverride(LastSeenBy,Range(NearestEnemyOf(Myself),22))
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("potn26",LastSeenBy)  // ~Potion of Explosions~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  CheckStat(Myself,0,TRUE_SIGHT)
  OR(3)
    HaveSpell(WIZARD_TRUE_SIGHT)
    HaveSpell(CLERIC_TRUE_SIGHT)
    HaveSpell(WIZARD_ORACLE)
  OR(2)
    !Detect(NearestEnemyOf(Myself))
    !StateCheck(NearestEnemyOf(Myself),STATE_ILLUSIONS)
  OR(2)
    !Detect(SecondNearestEnemyOf(Myself))
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_ILLUSIONS)
  OR(2)
    !Detect(ThirdNearestEnemyOf(Myself))
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_ILLUSIONS)
  OR(2)
    !Detect(FourthNearestEnemyOf(Myself))
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_ILLUSIONS)
  OR(2)
    !Detect(FifthNearestEnemyOf(Myself))
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_ILLUSIONS)
  OR(2)
    !Detect(SixthNearestEnemyOf(Myself))
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_ILLUSIONS)
  OR(2)
    !Detect(SeventhNearestEnemyOf(Myself))
    !StateCheck(SeventhNearestEnemyOf(Myself),STATE_ILLUSIONS)
  OR(2)
    !Detect(EighthNearestEnemyOf(Myself))
    !StateCheck(EighthNearestEnemyOf(Myself),STATE_ILLUSIONS)
  OR(2)
    !Detect(NinthNearestEnemyOf(Myself))
    !StateCheck(NinthNearestEnemyOf(Myself),STATE_ILLUSIONS)
  OR(2)
    !Detect(TenthNearestEnemyOf(Myself))
    !StateCheck(TenthNearestEnemyOf(Myself),STATE_ILLUSIONS)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  HaveSpell(WIZARD_TRUE_SIGHT)
  Detect(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  StateCheck(LastSeenBy,STATE_ILLUSIONS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_TRUE_SIGHT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  HaveSpell(CLERIC_TRUE_SIGHT)
  Detect(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  StateCheck(LastSeenBy,STATE_ILLUSIONS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_TRUE_SIGHT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  HaveSpell(WIZARD_ORACLE)
  Detect(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  StateCheck(LastSeenBy,STATE_ILLUSIONS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_ORACLE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,EVILCUTOFF)
  Detect([GOODCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(CLERIC_INVISIBILITY_PURGE)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_INVISIBILITY_PURGE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,EVILCUTOFF)
  Detect([GOODCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(WIZARD_DETECT_INVISIBILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,EVILCUTOFF)
  Detect([GOODCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(WIZARD_TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_TRUE_SIGHT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,EVILCUTOFF)
  Detect([GOODCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(CLERIC_TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_TRUE_SIGHT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,EVILCUTOFF)
  Detect([GOODCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(WIZARD_ORACLE)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_ORACLE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,GOODCUTOFF)
  Detect([EVILCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(CLERIC_INVISIBILITY_PURGE)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_INVISIBILITY_PURGE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,GOODCUTOFF)
  Detect([EVILCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(WIZARD_DETECT_INVISIBILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,GOODCUTOFF)
  Detect([EVILCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(WIZARD_TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_TRUE_SIGHT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,GOODCUTOFF)
  Detect([EVILCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(CLERIC_TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_TRUE_SIGHT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  CheckStat(Myself,0,TRUE_SIGHT)
  Allegiance(Myself,GOODCUTOFF)
  Detect([EVILCUTOFF])
  !See(LastSeenBy(Myself))
  HaveSpell(WIZARD_ORACLE)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_ORACLE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  HaveSpell(WIZARD_BREACH)
  OR(2)
    !See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    !CheckStatGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0,STONESKINS)
  OR(2)
    !See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    !CheckSpellState(NearestEnemyOfType([0.0.0.MAGE_ALL]),BUFF_PRO_WEAPONS)
  OR(2)
    !See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
    !CheckStatGT(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),0,STONESKINS)
  OR(2)
    !See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
    !CheckSpellState(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),BUFF_PRO_WEAPONS)
  OR(2)
    !See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
    !CheckStatGT(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]),0,STONESKINS)
  OR(2)
    !See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
    !CheckSpellState(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]),BUFF_PRO_WEAPONS)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_BREACH)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  OR(2)
    CheckSpellState(LastSeenBy,BUFF_PRO_WEAPONS)
    CheckStatGT(LastSeenBy,0,STONESKINS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_BREACH)
  RESPONSE #100
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  HaveSpell(WIZARD_BREACH)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    !CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    !CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    !CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    !CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_BREACH)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  OR(2)
    CheckSpellState(LastSeenBy,BUFF_PRO_EFFECTS)
    CheckSpellState(LastSeenBy,BUFF_PRO_DAMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_BREACH)
  RESPONSE #100
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(3)
    HaveSpell(WIZARD_PIERCE_MAGIC)
    HaveSpell(WIZARD_SECRET_WORD)
    HaveSpell(WIZARD_SPELL_THRUST)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_SPELLS)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_SPELLS)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_SPELLS)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    !CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_SPELLS)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    !CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_SPELLS)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_PIERCE_MAGIC)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  CheckSpellState(LastSeenBy,BUFF_PRO_SPELLS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_PIERCE_MAGIC)
  RESPONSE #100
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_SECRET_WORD)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  CheckSpellState(LastSeenBy,BUFF_PRO_SPELLS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_SECRET_WORD)
  RESPONSE #100
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_SPELL_THRUST)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  CheckSpellState(LastSeenBy,BUFF_PRO_SPELLS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_SPELL_THRUST)
  RESPONSE #100
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  HaveSpell(WIZARD_SLOW)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !StateCheck(NearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(SixthNearestEnemyOf(Myself))
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(SeventhNearestEnemyOf(Myself))
    !StateCheck(SeventhNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(EighthNearestEnemyOf(Myself))
    !StateCheck(EighthNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(NinthNearestEnemyOf(Myself))
    !StateCheck(NinthNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(TenthNearestEnemyOf(Myself))
    !StateCheck(TenthNearestEnemyOf(Myself),STATE_HASTED)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_SLOW)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  StateCheck(LastSeenBy,STATE_HASTED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_SLOW)
  RESPONSE #35
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  HaveSpell(WIZARD_SLOW)
  OR(3)
    !See(NearestEnemyOf(Myself))
    !TriggerOverride(NearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
  OR(3)
    !See(SecondNearestEnemyOf(Myself))
    !TriggerOverride(SecondNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
  OR(3)
    !See(ThirdNearestEnemyOf(Myself))
    !TriggerOverride(ThirdNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
  OR(3)
    !See(FourthNearestEnemyOf(Myself))
    !TriggerOverride(FourthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
  OR(3)
    !See(FifthNearestEnemyOf(Myself))
    !TriggerOverride(FifthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
  OR(3)
    !See(SixthNearestEnemyOf(Myself))
    !TriggerOverride(SixthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
  OR(3)
    !See(SeventhNearestEnemyOf(Myself))
    !TriggerOverride(SeventhNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(SeventhNearestEnemyOf(Myself),STATE_SLOWED)
  OR(3)
    !See(EighthNearestEnemyOf(Myself))
    !TriggerOverride(EighthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(EighthNearestEnemyOf(Myself),STATE_SLOWED)
  OR(3)
    !See(NinthNearestEnemyOf(Myself))
    !TriggerOverride(NinthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(NinthNearestEnemyOf(Myself),STATE_SLOWED)
  OR(3)
    !See(TenthNearestEnemyOf(Myself))
    !TriggerOverride(TenthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(TenthNearestEnemyOf(Myself),STATE_SLOWED)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_SLOW)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),15))
  !StateCheck(LastSeenBy,STATE_SLOWED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_SLOW)
  RESPONSE #35
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  OR(2)
    HaveSpell(WIZARD_HASTE)
    HaveSpell(WIZARD_HASTE)
  OR(2)
    !See(NearestAllyOf(Myself))
    !StateCheck(NearestAllyOf(Myself),STATE_SLOWED)
  OR(2)
    !See(SecondNearestAllyOf(Myself))
    !StateCheck(SecondNearestAllyOf(Myself),STATE_SLOWED)
  OR(2)
    !See(ThirdNearestAllyOf(Myself))
    !StateCheck(ThirdNearestAllyOf(Myself),STATE_SLOWED)
  OR(2)
    !See(FourthNearestAllyOf(Myself))
    !StateCheck(FourthNearestAllyOf(Myself),STATE_SLOWED)
  OR(2)
    !See(FifthNearestAllyOf(Myself))
    !StateCheck(FifthNearestAllyOf(Myself),STATE_SLOWED)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_HASTE)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  DifficultyGT(NORMAL)
  StateCheck(LastSeenBy,STATE_SLOWED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_haste_timer","locals",FOUR_ROUNDS)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_HASTE)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_HASTE)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !DifficultyGT(NORMAL)
  StateCheck(LastSeenBy,STATE_SLOWED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_haste_timer","locals",FOUR_ROUNDS)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_HASTE)
  RESPONSE #35
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  !GlobalTimerNotExpired("bd_haste_timer","locals")
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  OR(2)
    HaveSpell(WIZARD_HASTE)
    HaveSpell(WIZARD_HASTE)
  OR(3)
    !See(NearestAllyOf(Myself))
    !TriggerOverride(NearestAllyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(NearestAllyOf(Myself),STATE_HASTED)
  OR(3)
    !See(SecondNearestAllyOf(Myself))
    !TriggerOverride(SecondNearestAllyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(SecondNearestAllyOf(Myself),STATE_HASTED)
  OR(3)
    !See(ThirdNearestAllyOf(Myself))
    !TriggerOverride(ThirdNearestAllyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(ThirdNearestAllyOf(Myself),STATE_HASTED)
  OR(3)
    !See(FourthNearestAllyOf(Myself))
    !TriggerOverride(FourthNearestAllyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(FourthNearestAllyOf(Myself),STATE_HASTED)
  OR(3)
    !See(FifthNearestAllyOf(Myself))
    !TriggerOverride(FifthNearestAllyOf(Myself),Range(NearestAllyOf(Myself),15))
    StateCheck(FifthNearestAllyOf(Myself),STATE_HASTED)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !GlobalTimerNotExpired("bd_haste_timer","locals")
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_HASTE)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  DifficultyGT(NORMAL)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),15))
  !StateCheck(LastSeenBy,STATE_HASTED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_haste_timer","locals",FOUR_ROUNDS)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_HASTE)
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !GlobalTimerNotExpired("bd_haste_timer","locals")
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_HASTE)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !DifficultyGT(NORMAL)
  TriggerOverride(LastSeenBy,Range(NearestAllyOf(Myself),15))
  !StateCheck(LastSeenBy,STATE_HASTED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_haste_timer","locals",FOUR_ROUNDS)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_HASTE)
  RESPONSE #35
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !StateCheck(NearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    !CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    !CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    !CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    !CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  OR(2)
    !See(SixthNearestEnemyOf(Myself))
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_HASTED)
  OR(2)
    !See(SixthNearestEnemyOf(Myself))
    !CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
  OR(2)
    !See(SixthNearestEnemyOf(Myself))
    !CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_EFFECTS)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  OR(3)
    CheckSpellState(LastSeenBy,BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy,BUFF_PRO_EFFECTS)
    StateCheck(LastSeenBy,STATE_HASTED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_DISPEL_MAGIC)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Range(NearestEnemyOf(Myself),30)
  HaveSpell(CLERIC_DEFENSIVE_HARMONY)
  Range(FourthNearestAllyOf(Myself),20)
  OR(2)
    CheckStat(NearestAllyOf(Myself),0,CLERIC_DEFENSIVE_HARMONY)
    CheckStat(SecondNearestAllyOf(Myself),0,CLERIC_DEFENSIVE_HARMONY)
  OR(2)
    CheckStat(ThirdNearestAllyOf(Myself),0,CLERIC_DEFENSIVE_HARMONY)
    CheckStat(FourthNearestAllyOf(Myself),0,CLERIC_DEFENSIVE_HARMONY)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_DEFENSIVE_HARMONY)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Range(NearestEnemyOf(Myself),30)
  HaveSpell(CLERIC_STRENGTH_OF_ONE)
  Range(FourthNearestAllyOf(Myself),20)
  OR(2)
    CheckStatLT(NearestAllyOf(Myself),18,STR)
    CheckStatLT(SecondNearestAllyOf(Myself),18,STR)
  OR(2)
    CheckStatLT(ThirdNearestAllyOf(Myself),18,STR)
    CheckStatLT(FourthNearestAllyOf(Myself),18,STR)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_STRENGTH_OF_ONE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Range(NearestEnemyOf(Myself),30)
  HaveSpell(CLERIC_CHANT)
  Range(FourthNearestAllyOf(Myself),20)
  OR(2)
    !StateCheck(NearestAllyOf(Myself),STATE_CHANT)
    !StateCheck(SecondNearestAllyOf(Myself),STATE_CHANT)
  OR(2)
    !StateCheck(ThirdNearestAllyOf(Myself),STATE_CHANT)
    !StateCheck(FourthNearestAllyOf(Myself),STATE_CHANT)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_CHANT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Range(NearestEnemyOf(Myself),30)
  HaveSpell(CLERIC_BLESS)
  Range(FourthNearestAllyOf(Myself),20)
  OR(2)
    !StateCheck(NearestAllyOf(Myself),STATE_BLESS)
    !StateCheck(SecondNearestAllyOf(Myself),STATE_BLESS)
  OR(2)
    !StateCheck(ThirdNearestAllyOf(Myself),STATE_BLESS)
    !StateCheck(FourthNearestAllyOf(Myself),STATE_BLESS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_BLESS)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(NearestEnemyOfType([0.0.0.0.0.0.MASK_EVIL]))
  HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
  Range(FourthNearestAllyOf(Myself),20)
  OR(2)
    CheckStat(NearestAllyOf(Myself),0,PROTECTION_FROM_EVIL)
    CheckStat(SecondNearestAllyOf(Myself),0,PROTECTION_FROM_EVIL)
  OR(2)
    CheckStat(ThirdNearestAllyOf(Myself),0,PROTECTION_FROM_EVIL)
    CheckStat(FourthNearestAllyOf(Myself),0,PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  HaveSpell(CLERIC_REMOVE_PARALYSIS)
  OR(2)
    !See(NearestAllyOf(Myself))
    !StateCheck(NearestAllyOf(Myself),40)
  OR(2)
    !See(SecondNearestAllyOf(Myself))
    !StateCheck(SecondNearestAllyOf(Myself),40)
  OR(2)
    !See(ThirdNearestAllyOf(Myself))
    !StateCheck(ThirdNearestAllyOf(Myself),40)
  OR(2)
    !See(FourthNearestAllyOf(Myself))
    !StateCheck(FourthNearestAllyOf(Myself),40)
  OR(2)
    !See(FifthNearestAllyOf(Myself))
    !StateCheck(FifthNearestAllyOf(Myself),40)
  OR(2)
    !See(SixthNearestAllyOf(Myself))
    !StateCheck(SixthNearestAllyOf(Myself),40)
  OR(2)
    !See(SeventhNearestAllyOf(Myself))
    !StateCheck(SeventhNearestAllyOf(Myself),40)
  OR(2)
    !See(EighthNearestAllyOf(Myself))
    !StateCheck(EighthNearestAllyOf(Myself),40)
  OR(2)
    !See(NinthNearestAllyOf(Myself))
    !StateCheck(NinthNearestAllyOf(Myself),40)
  OR(2)
    !See(TenthNearestAllyOf(Myself))
    !StateCheck(TenthNearestAllyOf(Myself),40)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_REMOVE_PARALYSIS)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  StateCheck(LastSeenBy,40)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_REMOVE_PARALYSIS)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    HaveSpell(WIZARD_RESIST_FEAR)
    HaveSpell(CLERIC_REMOVE_FEAR)
  OR(2)
    !See(NearestAllyOf(Myself))
    !StateCheck(NearestAllyOf(Myself),STATE_PANIC)
  OR(2)
    !See(SecondNearestAllyOf(Myself))
    !StateCheck(SecondNearestAllyOf(Myself),STATE_PANIC)
  OR(2)
    !See(ThirdNearestAllyOf(Myself))
    !StateCheck(ThirdNearestAllyOf(Myself),STATE_PANIC)
  OR(2)
    !See(FourthNearestAllyOf(Myself))
    !StateCheck(FourthNearestAllyOf(Myself),STATE_PANIC)
  OR(2)
    !See(FifthNearestAllyOf(Myself))
    !StateCheck(FifthNearestAllyOf(Myself),STATE_PANIC)
  OR(2)
    !See(SixthNearestAllyOf(Myself))
    !StateCheck(SixthNearestAllyOf(Myself),STATE_PANIC)
  OR(2)
    !See(SeventhNearestAllyOf(Myself))
    !StateCheck(SeventhNearestAllyOf(Myself),STATE_PANIC)
  OR(2)
    !See(EighthNearestAllyOf(Myself))
    !StateCheck(EighthNearestAllyOf(Myself),STATE_PANIC)
  OR(2)
    !See(NinthNearestAllyOf(Myself))
    !StateCheck(NinthNearestAllyOf(Myself),STATE_PANIC)
  OR(2)
    !See(TenthNearestAllyOf(Myself))
    !StateCheck(TenthNearestAllyOf(Myself),STATE_PANIC)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_RESIST_FEAR)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  StateCheck(LastSeenBy,STATE_PANIC)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_RESIST_FEAR)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_REMOVE_FEAR)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  StateCheck(LastSeenBy,STATE_PANIC)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_REMOVE_FEAR)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  OR(2)
    HaveSpell(WIZARD_FINGER_OF_DEATH)
    HaveSpell(WIZARD_FLESH_TO_STONE)
  OR(3)
    !See(NearestEnemyOf(Myself))
    RandomNumGT(4,2)
    !CheckStat(NearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  OR(3)
    !See(SecondNearestEnemyOf(Myself))
    RandomNumGT(4,3)
    !CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    !CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    !CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    !CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  OR(2)
    !See(NearestEnemyOf(Myself))
    !CheckStat(NearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    !CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_FINGER_OF_DEATH)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  CheckStat(LastSeenBy,0,WIZARD_SPELL_TURNING)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_FINGER_OF_DEATH)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_FLESH_TO_STONE)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  CheckStat(LastSeenBy,0,WIZARD_SPELL_TURNING)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_FLESH_TO_STONE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !Allegiance(Myself,GOODBUTBLUE)
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_INVISIBLE_STALKER)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_INVISIBLE_STALKER)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !Allegiance(Myself,GOODBUTBLUE)
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_AERIAL_SERVANT)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_AERIAL_SERVANT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !Allegiance(Myself,GOODBUTBLUE)
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_CONJURE_ANIMALS)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_CONJURE_ANIMALS)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !Allegiance(Myself,GOODBUTBLUE)
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_ANIMATE_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_ANIMATE_DEAD)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !Allegiance(Myself,GOODBUTBLUE)
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_ANIMAL_SUMMONING_3)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_ANIMAL_SUMMONING_3)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !Allegiance(Myself,GOODBUTBLUE)
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_SPIDER_SPAWN)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_SPIDER_SPAWN)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !Allegiance(Myself,GOODBUTBLUE)
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_MONSTER_SUMMONING_2)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,WIZARD_MONSTER_SUMMONING_2)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !Allegiance(Myself,GOODBUTBLUE)
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_ANIMAL_SUMMONING_2)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_ANIMAL_SUMMONING_2)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  !Allegiance(Myself,GOODBUTBLUE)
  Range(NearestEnemyOf(Myself),30)
  OR(2)
    DifficultyGT(EASIEST)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_ANIMATE_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(Myself,CLERIC_ANIMATE_DEAD)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  DifficultyGT(EASY)
  HaveSpell(WIZARD_TELEPORT_FIELD)
  OR(2)
    !See(NearestEnemyOf(Myself))
    RandomNumGT(4,2)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    RandomNumGT(4,3)
  !See(ThirdNearestEnemyOf(Myself))
  !See(NearestEnemyOf(Myself))
  !See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  DifficultyGT(EASY)
  HaveSpell(WIZARD_TELEPORT_FIELD)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_TELEPORT_FIELD)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  OR(5)
    HaveSpell(WIZARD_CHAOS)
    HaveSpell(WIZARD_CONFUSION)
    HaveSpell(CLERIC_GREATER_COMMAND)
    HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
    HaveSpell(WIZARD_GLITTERDUST)
  OR(2)
    !See(NearestEnemyOf(Myself))
    StateCheck(NearestEnemyOf(Myself),STATE_DEBUFF)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    StateCheck(SecondNearestEnemyOf(Myself),STATE_DEBUFF)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_DEBUFF)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    StateCheck(FourthNearestEnemyOf(Myself),STATE_DEBUFF)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    StateCheck(FifthNearestEnemyOf(Myself),STATE_DEBUFF)
  OR(2)
    !See(SixthNearestEnemyOf(Myself))
    StateCheck(SixthNearestEnemyOf(Myself),STATE_DEBUFF)
  OR(2)
    !See(SeventhNearestEnemyOf(Myself))
    StateCheck(SeventhNearestEnemyOf(Myself),STATE_DEBUFF)
  OR(2)
    !See(EighthNearestEnemyOf(Myself))
    StateCheck(EighthNearestEnemyOf(Myself),STATE_DEBUFF)
  OR(2)
    !See(NinthNearestEnemyOf(Myself))
    StateCheck(NinthNearestEnemyOf(Myself),STATE_DEBUFF)
  OR(2)
    !See(TenthNearestEnemyOf(Myself))
    StateCheck(TenthNearestEnemyOf(Myself),STATE_DEBUFF)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_CHAOS)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DEBUFF)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_CHAOS)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_CONFUSION)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DEBUFF)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_CONFUSION)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(CLERIC_GREATER_COMMAND)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DEBUFF)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_GREATER_COMMAND)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DEBUFF)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_EMOTION_HOPELESSNESS)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  OR(2)
    DifficultyGT(EASY)
    Allegiance(Myself,GOODCUTOFF)
  HaveSpell(WIZARD_GLITTERDUST)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DEBUFF)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_GLITTERDUST)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  HaveSpell(WIZARD_POWER_WORD_SILENCE)
  OR(3)
    !See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(NearestEnemyOfType([0.0.0.MAGE_ALL]),0,WIZARD_SPELL_TURNING)
  OR(3)
    !See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),0,WIZARD_SPELL_TURNING)
  OR(3)
    !See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0,WIZARD_SPELL_TURNING)
  OR(3)
    !See(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]),0,WIZARD_SPELL_TURNING)
  OR(3)
    !See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.BARD_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(NearestEnemyOfType([0.0.0.BARD_ALL]),0,WIZARD_SPELL_TURNING)
  OR(3)
    !See(SecondNearestEnemyOfType([0.0.0.BARD_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.BARD_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.BARD_ALL]),0,WIZARD_SPELL_TURNING)
  OR(3)
    !See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(NearestEnemyOfType([0.0.0.DRUID_ALL]),0,WIZARD_SPELL_TURNING)
  OR(3)
    !See(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]),0,WIZARD_SPELL_TURNING)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_POWER_WORD_SILENCE)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED_CASTING)
  CheckStat(LastSeenBy,0,WIZARD_SPELL_TURNING)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_POWER_WORD_SILENCE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  DifficultyGT(EASIEST)
  HaveSpell(CLERIC_SILENCE_15_FOOT)
  OR(5)
    !See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    TriggerOverride(NearestEnemyOfType([0.0.0.MAGE_ALL]),Range(NearestEnemyOfType([0.0.0.MAGE_ALL]),15))
    TriggerOverride(NearestEnemyOfType([0.0.0.MAGE_ALL]),Range(NearestEnemyOfType([0.0.0.CLERIC_ALL]),15))
    StateCheck(NearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(NearestEnemyOfType([0.0.0.MAGE_ALL]),0,WIZARD_SPELL_TURNING)
  OR(5)
    !See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),Range(NearestEnemyOfType([0.0.0.MAGE_ALL]),15))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),Range(NearestEnemyOfType([0.0.0.CLERIC_ALL]),15))
    StateCheck(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),0,WIZARD_SPELL_TURNING)
  OR(5)
    !See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    TriggerOverride(NearestEnemyOfType([0.0.0.CLERIC_ALL]),Range(NearestEnemyOfType([0.0.0.MAGE_ALL]),15))
    TriggerOverride(NearestEnemyOfType([0.0.0.CLERIC_ALL]),Range(NearestEnemyOfType([0.0.0.CLERIC_ALL]),15))
    StateCheck(NearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0,WIZARD_SPELL_TURNING)
  OR(5)
    !See(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]),Range(NearestEnemyOfType([0.0.0.MAGE_ALL]),15))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]),Range(NearestEnemyOfType([0.0.0.CLERIC_ALL]),15))
    StateCheck(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]),0,WIZARD_SPELL_TURNING)
  OR(5)
    !See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    TriggerOverride(NearestEnemyOfType([0.0.0.BARD_ALL]),Range(NearestEnemyOfType([0.0.0.MAGE_ALL]),15))
    TriggerOverride(NearestEnemyOfType([0.0.0.BARD_ALL]),Range(NearestEnemyOfType([0.0.0.CLERIC_ALL]),15))
    StateCheck(NearestEnemyOfType([0.0.0.BARD_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(NearestEnemyOfType([0.0.0.BARD_ALL]),0,WIZARD_SPELL_TURNING)
  OR(5)
    !See(SecondNearestEnemyOfType([0.0.0.BARD_ALL]))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.BARD_ALL]),Range(NearestEnemyOfType([0.0.0.MAGE_ALL]),15))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.BARD_ALL]),Range(NearestEnemyOfType([0.0.0.CLERIC_ALL]),15))
    StateCheck(SecondNearestEnemyOfType([0.0.0.BARD_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.BARD_ALL]),0,WIZARD_SPELL_TURNING)
  OR(5)
    !See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
    TriggerOverride(NearestEnemyOfType([0.0.0.DRUID_ALL]),Range(NearestEnemyOfType([0.0.0.MAGE_ALL]),15))
    TriggerOverride(NearestEnemyOfType([0.0.0.DRUID_ALL]),Range(NearestEnemyOfType([0.0.0.CLERIC_ALL]),15))
    StateCheck(NearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(NearestEnemyOfType([0.0.0.DRUID_ALL]),0,WIZARD_SPELL_TURNING)
  OR(5)
    !See(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]),Range(NearestEnemyOfType([0.0.0.MAGE_ALL]),15))
    TriggerOverride(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]),Range(NearestEnemyOfType([0.0.0.CLERIC_ALL]),15))
    StateCheck(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_DISABLED_CASTING)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]),0,WIZARD_SPELL_TURNING)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  DifficultyGT(EASIEST)
  HaveSpell(CLERIC_SILENCE_15_FOOT)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !TriggerOverride(LastSeenBy,Range(NearestEnemyOfType([0.0.0.MAGE_ALL]),15))
  !TriggerOverride(LastSeenBy,Range(NearestEnemyOfType([0.0.0.CLERIC_ALL]),15))
  !StateCheck(LastSeenBy,STATE_DISABLED_CASTING)
  CheckStat(LastSeenBy,0,WIZARD_SPELL_TURNING)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_SILENCE_15_FOOT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    HaveSpell(CLERIC_MISCAST_MAGIC)
    HaveSpell(WIZARD_DEAFNESS)
  OR(4)
    !See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(NearestEnemyOfType([0.0.0.MAGE_ALL]),50,SPELLFAILUREMAGE)
    !CheckStat(NearestEnemyOfType([0.0.0.MAGE_ALL]),0,WIZARD_SPELL_TURNING)
  OR(4)
    !See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),50,SPELLFAILUREMAGE)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]),0,WIZARD_SPELL_TURNING)
  OR(4)
    !See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
    StateCheck(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]),50,SPELLFAILUREMAGE)
    !CheckStat(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]),0,WIZARD_SPELL_TURNING)
  OR(4)
    !See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.BARD_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(NearestEnemyOfType([0.0.0.BARD_ALL]),50,SPELLFAILUREMAGE)
    !CheckStat(NearestEnemyOfType([0.0.0.BARD_ALL]),0,WIZARD_SPELL_TURNING)
  OR(4)
    !See(SecondNearestEnemyOfType([0.0.0.BARD_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.BARD_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(SecondNearestEnemyOfType([0.0.0.BARD_ALL]),50,SPELLFAILUREMAGE)
    !CheckStat(SecondNearestEnemyOfType([0.0.0.BARD_ALL]),0,WIZARD_SPELL_TURNING)
  OR(4)
    !See(ThirdNearestEnemyOfType([0.0.0.BARD_ALL]))
    StateCheck(ThirdNearestEnemyOfType([0.0.0.BARD_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(ThirdNearestEnemyOfType([0.0.0.BARD_ALL]),50,SPELLFAILUREMAGE)
    !CheckStat(ThirdNearestEnemyOfType([0.0.0.BARD_ALL]),0,WIZARD_SPELL_TURNING)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_MISCAST_MAGIC)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED_CASTING)
  CheckStatLT(LastSeenBy,50,SPELLFAILUREMAGE)
  CheckStat(LastSeenBy,0,WIZARD_SPELL_TURNING)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_MISCAST_MAGIC)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_DEAFNESS)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED_CASTING)
  CheckStatLT(LastSeenBy,50,SPELLFAILUREMAGE)
  CheckStat(LastSeenBy,0,WIZARD_SPELL_TURNING)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_DEAFNESS)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    HaveSpell(CLERIC_MISCAST_MAGIC)
    HaveSpell(WIZARD_DEAFNESS)
  OR(3)
    !See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),50,SPELLFAILUREPRIEST)
  OR(3)
    !See(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(SecondNearestEnemyOfType([0.0.0.CLERIC_ALL]),50,SPELLFAILUREPRIEST)
  OR(3)
    !See(ThirdNearestEnemyOfType([0.0.0.CLERIC_ALL]))
    StateCheck(ThirdNearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(ThirdNearestEnemyOfType([0.0.0.CLERIC_ALL]),50,SPELLFAILUREPRIEST)
  OR(3)
    !See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(NearestEnemyOfType([0.0.0.DRUID_ALL]),50,SPELLFAILUREPRIEST)
  OR(3)
    !See(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(SecondNearestEnemyOfType([0.0.0.DRUID_ALL]),50,SPELLFAILUREPRIEST)
  OR(3)
    !See(ThirdNearestEnemyOfType([0.0.0.DRUID_ALL]))
    StateCheck(ThirdNearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_DISABLED_CASTING)
    !CheckStatLT(ThirdNearestEnemyOfType([0.0.0.DRUID_ALL]),50,SPELLFAILUREPRIEST)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_MISCAST_MAGIC)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED_CASTING)
  CheckStatLT(LastSeenBy,50,SPELLFAILUREPRIEST)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_MISCAST_MAGIC)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_DEAFNESS)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED_CASTING)
  CheckStatLT(LastSeenBy,50,SPELLFAILUREPRIEST)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_DEAFNESS)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    HaveSpell(WIZARD_HORROR)
    HasItem("wand02",Myself)  // ~Wand of Fear~
  OR(3)
    !See(NearestEnemyOf(Myself))
    CheckSpellState(NearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(SecondNearestEnemyOf(Myself))
    CheckSpellState(SecondNearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(ThirdNearestEnemyOf(Myself))
    CheckSpellState(ThirdNearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(FourthNearestEnemyOf(Myself))
    CheckSpellState(FourthNearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(FifthNearestEnemyOf(Myself))
    CheckSpellState(FifthNearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(SixthNearestEnemyOf(Myself))
    CheckSpellState(SixthNearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(SeventhNearestEnemyOf(Myself))
    CheckSpellState(SeventhNearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(EighthNearestEnemyOf(Myself))
    CheckSpellState(EighthNearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(NinthNearestEnemyOf(Myself))
    CheckSpellState(NinthNearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(TenthNearestEnemyOf(Myself))
    CheckSpellState(TenthNearestEnemyOf(Myself),RESIST_FEAR)
    StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_HORROR)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !CheckSpellState(LastSeenBy,RESIST_FEAR)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_HORROR)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HasItem("wand02",Myself)  // ~Wand of Fear~
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !CheckSpellState(LastSeenBy,RESIST_FEAR)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("wand02",LastSeenBy)  // ~Wand of Fear~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    HaveSpell(WIZARD_GREATER_MALISON)
    HaveSpell(CLERIC_DOOM)
  OR(2)
    !See(NearestEnemyOf(Myself))
    CheckSpellState(NearestEnemyOf(Myself),MALISON)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    CheckSpellState(SecondNearestEnemyOf(Myself),MALISON)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    CheckSpellState(ThirdNearestEnemyOf(Myself),MALISON)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_GREATER_MALISON)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !CheckSpellState(LastSeenBy,MALISON)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_GREATER_MALISON)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_DOOM)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !CheckSpellState(LastSeenBy,MALISON)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_DOOM)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(14)
    HaveSpell(WIZARD_POWER_WORD_STUN)
    HaveSpell(WIZARD_DOMINATION)
    HaveSpell(LATHANDER_HOLD_UNDEAD)
    HaveSpell(WIZARD_HOLD_UNDEAD)
    HaveSpell(WIZARD_HOLD_PERSON)
    HaveSpell(CLERIC_HOLD_PERSON)
    HaveSpell(WIZARD_HOLD_MONSTER)
    HasItem("wand04",Myself)  // ~Wand of Paralyzation~
    HaveSpell(WIZARD_DIRE_CHARM)
    HaveSpell(WIZARD_FEEBLEMIND)
    HaveSpell(CLERIC_RIGID_THINKING)
    HaveSpell(WIZARD_SPOOK)
    HaveSpell(CLERIC_COMMAND)
    HaveSpell(WIZARD_CHARM_PERSON)
  OR(3)
    !See(NearestEnemyOf(Myself))
    RandomNumGT(8,4)
    StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(SecondNearestEnemyOf(Myself))
    RandomNumGT(8,6)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
    !See(ThirdNearestEnemyOf(Myself))
    RandomNumGT(8,7)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(FourthNearestEnemyOf(Myself))
    StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(FifthNearestEnemyOf(Myself))
    StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(SixthNearestEnemyOf(Myself))
    StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(SeventhNearestEnemyOf(Myself))
    StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(EighthNearestEnemyOf(Myself))
    StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(NinthNearestEnemyOf(Myself))
    StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(TenthNearestEnemyOf(Myself))
    StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(NearestEnemyOf(Myself))
    StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  OR(2)
    !See(ThirdNearestEnemyOf(Myself))
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  HPLT(LastSeenBy,90)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_POWER_WORD_STUN)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_DOMINATION)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_DOMINATION)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(LATHANDER_HOLD_UNDEAD)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  General(LastSeenBy,UNDEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,LATHANDER_HOLD_UNDEAD)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_HOLD_UNDEAD)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  General(LastSeenBy,UNDEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_HOLD_UNDEAD)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_HOLD_PERSON)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  General(LastSeenBy,HUMANOID)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_HOLD_PERSON)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_HOLD_PERSON)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  General(LastSeenBy,HUMANOID)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_HOLD_PERSON)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_HOLD_MONSTER)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_HOLD_MONSTER)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HasItem("wand04",Myself)  // ~Wand of Paralyzation~
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("wand04",LastSeenBy)  // ~Wand of Paralyzation~
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_DIRE_CHARM)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  General(LastSeenBy,HUMANOID)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_DIRE_CHARM)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_FEEBLEMIND)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_FEEBLEMIND)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_RIGID_THINKING)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_RIGID_THINKING)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_SPOOK)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_SPOOK)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_COMMAND)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_COMMAND)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_CHARM_PERSON)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  General(LastSeenBy,HUMANOID)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_CHARM_PERSON)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(2)
    HaveSpell(WIZARD_RAY_OF_ENFEEBLEMENT)
    HaveSpell(WIZARD_BLINDNESS)
  OR(3)
    !See(NearestEnemyOfType([0.0.0.FIGHTER_ALL]))
    RandomNumGT(4,2)
    StateCheck(NearestEnemyOfType([0.0.0.FIGHTER_ALL]),STATE_DEBUFF)
  OR(3)
    !See(SecondNearestEnemyOfType([0.0.0.FIGHTER_ALL]))
    RandomNumGT(4,3)
    StateCheck(SecondNearestEnemyOfType([0.0.0.FIGHTER_ALL]),STATE_DEBUFF)
  OR(2)
    !See(ThirdNearestEnemyOfType([0.0.0.FIGHTER_ALL]))
    StateCheck(ThirdNearestEnemyOfType([0.0.0.FIGHTER_ALL]),STATE_DEBUFF)
  OR(2)
    !See(NearestEnemyOfType([0.0.0.FIGHTER_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.FIGHTER_ALL]),STATE_DEBUFF)
  OR(2)
    !See(SecondNearestEnemyOfType([0.0.0.FIGHTER_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.FIGHTER_ALL]),STATE_DEBUFF)
  OR(3)
    !See(NearestEnemyOfType([0.0.0.RANGER_ALL]))
    RandomNumGT(4,2)
    StateCheck(NearestEnemyOfType([0.0.0.RANGER_ALL]),STATE_DEBUFF)
  OR(3)
    !See(SecondNearestEnemyOfType([0.0.0.RANGER_ALL]))
    RandomNumGT(4,3)
    StateCheck(SecondNearestEnemyOfType([0.0.0.RANGER_ALL]),STATE_DEBUFF)
  OR(2)
    !See(ThirdNearestEnemyOfType([0.0.0.RANGER_ALL]))
    StateCheck(ThirdNearestEnemyOfType([0.0.0.RANGER_ALL]),STATE_DEBUFF)
  OR(2)
    !See(NearestEnemyOfType([0.0.0.RANGER_ALL]))
    StateCheck(NearestEnemyOfType([0.0.0.RANGER_ALL]),STATE_DEBUFF)
  OR(2)
    !See(SecondNearestEnemyOfType([0.0.0.RANGER_ALL]))
    StateCheck(SecondNearestEnemyOfType([0.0.0.RANGER_ALL]),STATE_DEBUFF)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_RAY_OF_ENFEEBLEMENT)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  CheckStatGT(LastSeenBy,17,STR)
  !StateCheck(LastSeenBy,STATE_DEBUFF)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_RAY_OF_ENFEEBLEMENT)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_BLINDNESS)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
  !StateCheck(LastSeenBy,STATE_DEBUFF)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_BLINDNESS)
  RESPONSE #50
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  Detect(Myself)
  OR(10)
    HaveSpell(CLERIC_FLAME_STRIKE)
    HaveSpell(WIZARD_FLAME_ARROW)
    HaveSpell(WIZARD_LIGHTNING_BOLT)
    HaveSpell(CLERIC_POISON)
    HasItem("wand06",Myself)  // ~Wand of Frost~
    HasItem("wand11",Myself)  // ~Wand of the Heavens~
    HaveSpell(WIZARD_MELF_ACID_ARROW)
    HaveSpell(WIZARD_MAGIC_MISSILE)
    HaveSpell(WIZARD_CHROMATIC_ORB)
    HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
  OR(2)
    !See(NearestEnemyOf(Myself))
    RandomNumGT(4,2)
  OR(2)
    !See(SecondNearestEnemyOf(Myself))
    RandomNumGT(4,3)
  !See(ThirdNearestEnemyOf(Myself))
  !See(NearestEnemyOf(Myself))
  !See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_FLAME_STRIKE)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_FLAME_STRIKE)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_FLAME_ARROW)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_FLAME_ARROW)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_LIGHTNING_BOLT)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_LIGHTNING_BOLT)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(CLERIC_POISON)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,CLERIC_POISON)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HasItem("wand06",Myself)  // ~Wand of Frost~
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("wand06",LastSeenBy)  // ~Wand of Frost~
    SetInterrupt(TRUE)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HasItem("wand11",Myself)  // ~Wand of the Heavens~
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    UseItem("wand11",LastSeenBy)  // ~Wand of the Heavens~
    SetInterrupt(TRUE)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_MELF_ACID_ARROW)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_MAGIC_MISSILE)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_MAGIC_MISSILE)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_CHROMATIC_ORB)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_CHROMATIC_ORB)
  RESPONSE #25
    Continue()
END

IF
  !GlobalTimerNotExpired("bd_cast","locals")
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
  See(LastSeenBy)
  !Range(LastSeenBy,0)
  !StateCheck(LastSeenBy,STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_cast","locals",ONE_ROUND)
    Spell(LastSeenBy,WIZARD_LARLOCH_MINOR_DRAIN)
  RESPONSE #25
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),5)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

